### ISSUE TITLE
Original source code for REGRIDPACK

### ISSUE THREAD

**Issue by camillem** [NCAR/NCAR-Classic-Libraries-for-Geophysics#2]
Hi,
I'm currently looking for the original source code of REGRIDPACK, which mentions `John C. Adams (NCAR 1999)` as author.
It used to be hosted at ftp://ftp.ucar.edu/ftp/dsl/lib/regridpack, which is no longer accessible (https://web.archive.org/web/20040216093851/http://www.scd.ucar.edu/softlib/REGRIDPACK.html ) .  

Do you plan to host a copy in this Github repo or would you know where it can be accessed from ?
Best regards,
Camille

**Comment by rvalent** [comment]
Hi Camille; I can email you a small gzip'd tarfile containing the
REGRIDPACK source code.  My email address is ***@***.***  Please
respond and I will send the source code via email.  Cheers! --Dick Valent,
NCAR

**Comment by camillem** [comment]
Thanks very much.
